FROM ubuntu

RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

  
RUN wget https://github.com/torognes/vsearch/releases/download/v2.28.1/vsearch-2.28.1-linux-x86_64.tar.gz
RUN tar xzf vsearch-2.28.1-linux-x86_64.tar.gz

RUN apt-get update && apt-get -y install rsync

ENV PATH="${PATH}:vsearch-2.22.1-linux-aarch64/bin/"

RUN wget https://mmseqs.com/latest/mmseqs-linux-arm64.tar.gz
RUN tar xzf mmseqs-linux-arm64.tar.gz
RUN mkdir apps
RUN mv mmseqs apps
ENV PATH="${PATH}:apps/mmseqs/bin/"

RUN wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/3.1.0/sratoolkit.3.1.0-ubuntu64.tar.gz
RUN tar -vxzf sratoolkit.3.1.0-ubuntu64.tar.gz
ENV PATH="${PATH}:sratoolkit.3.1.0-ubuntu64/bin/"

